# Generated by Django 4.2.1 on 2023-08-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DOWN', 'Fora do ar'), ('UP', 'Em funcionamento')], max_length=10)),
            ],
        ),
    ]
