# Generated by Django 4.2.1 on 2023-08-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DOWN', 'Fora do ar'), ('UP', 'Em funcionamento')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Aplications',
        ),
    ]
