# Generated by Django 4.2.1 on 2023-08-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farol', '0002_aplication_delete_aplications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplication',
            new_name='Aplicação',
        ),
    ]
