# Generated by Django 4.2.1 on 2023-08-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farol', '0003_rename_aplication_aplicação'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicação',
            options={'verbose_name_plural': 'Aplicações'},
        ),
    ]
