# Generated by Django 4.2.1 on 2023-08-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farol', '0004_alter_aplicação_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicação',
            old_name='name',
            new_name='nome',
        ),
    ]
