# Generated by Django 4.2.1 on 2023-08-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farol', '0005_rename_name_aplicação_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicação',
            name='status',
            field=models.CharField(choices=[('Fora do ar', 'DOWN'), ('Em funcionamento', 'Em funcionamento')], max_length=20),
        ),
    ]
